import './globals.css'
import type { Metadata } from 'next'
import Sidebar from '../components/LeftSide/Sidebar'
import RightSide from '../components/RightSide/RightSide'
import { Poppins } from 'next/font/google'
import { NextAuthProvider } from '../components/Providers/Providers'
import { authOptions } from '../lib/auth'
import {getServerSession} from 'next-auth'
import { Logout, NavLogin } from '../components/Buttons/Buttons'

const popins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en" className='scroll-smooth bg-gray-700'>
      <body className={`${popins.className}`}>
        <NextAuthProvider>
          <div className='flex justify-center'>
            <Sidebar />
            <div className='w-[60vw] my-8'>
              {children}
            </div>
            <RightSide />
            {
              session ? <p> <Logout></Logout> </p> : <NavLogin></NavLogin>
            }
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
